### PR TITLE
style login and signup views

### LINKED ISSUE #7: Improve UI of login and signup page
Currently the login and signup page look quite odd as both are placed at the centre of a wide bootstrap card, that spans the entire width of the screen. I guess it would look better if the bootstrap card was the exact size of the form and not the entire width of the screen. Any better UI design is also appreciated.

As this issue involves change in the UI, be sure to include screenshots/ screen-casts of the changes made.

### PR DESCRIPTION
**Pull request by DanielBiegler**
max-width, center and some helper utilities from bootstrap

fixes #7 

New Sign Up Form: 
image

New Login Form: 
image

### CODE REVIEW

**Comment by DanielBiegler** [comment]
@C-Anirudh are you ok with the new look?

**Comment by C-Anirudh** [comment]
> @C-Anirudh are you ok with the new look?

The new look is awesome.

Please pull the latest changes and resolve the merge conflicts.

**Comment by DanielBiegler** [comment]
Cool. Yeah on it.

**Comment by DanielBiegler** [comment]
Now with new changes

Login: 
image

Signup: 
image

**Comment by C-Anirudh** [comment]
@DanielBiegler Nice work !

**Pull request merged**
